#' 1D-to-2D Function Stream Plot for ggplot2
#'
#' These functions provide convenient ggplot2 layers for drawing streams
#' generated by mapping a one-dimensional input (typically time) to
#' two-dimensional coordinates. A user-defined function (`fun`) specifies the
#' mapping by taking a numeric scalar (e.g. time) and returning a numeric vector
#' of length 2 (representing \eqn{(x, y)}). The underlying [Stat_1d_2d] evaluates
#' `fun` over a time sequence spanning `tlim` in increments of `dt`, and
#' [GeomStream] renders the resulting path.
#'
#' In many cases these layers are useful for visualizing dynamic systems or
#' flows where a one-dimensional parameter (often time) drives movement in
#' two-dimensional space.
#'
#' @inheritParams ggplot2::geom_path
#'
#' @param mapping A set of aesthetic mappings created by [ggplot2::aes()].
#'   Additional aesthetics such as `color`, `size`, `linetype`, and `alpha` can
#'   be defined. The default mapping sets `color = after_stat(t)`.
#' @param data A data frame containing the input data. In many cases, no data
#'   needs to be supplied.
#' @param stat The statistical transformation to use on the data for this layer.
#'   Defaults to [Stat_1d_2d].
#' @param position Position adjustment, either as a string or the result of a
#'   call to a position adjustment function.
#' @param na.rm Logical. If `FALSE`, the default, missing values are removed
#'   with a warning. If `TRUE`, missing values are silently removed.
#' @param show.legend Logical. Should this layer be included in the legends?
#' @param inherit.aes Logical. If `FALSE`, overrides the default aesthetics
#'   rather than combining with them.
#' @param fun A function that defines the mapping from a scalar input (typically
#'   time) to a two-dimensional coordinate. It should take a numeric scalar and
#'   return a numeric vector of length 2 representing \eqn{(x, y)}.
#'   **(Required)**
#' @param tlim Numeric vector of length 2. The range of the time sequence,
#'   given as `c(t_start, t_end)`. Defaults to `c(0, 10)`.
#' @param dt Numeric. The time increment for evaluating `fun`. Defaults to
#'   `0.01`.
#' @param args List of additional arguments passed on to the function defined by
#'   `fun`.
#' @param tail_point Logical. If `TRUE`, a point is drawn at the tail (starting
#'   position) of the stream.
#' @param type Character. Rendering type passed to [ggvfields::GeomStream].
#'   Defaults to `"stream"`.
#' @param arrow A [grid::arrow()] specification to add arrowheads to the stream.
#'   Defaults to `NULL` (no arrowhead). Pass `grid::arrow()` to add one.
#' @param ... Other arguments passed on to [ggplot2::layer()].
#'
#' @section Computed variables:
#' These are calculated by the `stat` part of the layer and can be accessed
#' with [ggplot2::after_stat()].
#' \describe{
#'   \item{`after_stat(t)`}{Parameter values, typically time.}
#'   \item{`after_stat(x)`}{First coordinate returned by `fun`.}
#'   \item{`after_stat(y)`}{Second coordinate returned by `fun`.}
#' }
#'
#' @section Aesthetics:
#' `geom_function_1d_2d()` does not require input aesthetics when `fun` is
#' supplied. The default mapping sets `colour = after_stat(t)`. Additional path
#' and stream aesthetics such as `alpha`, `colour`/`color`, `group`,
#' `linetype`, and `linewidth` are passed to [ggvfields::GeomStream].
#'
#' @return A ggplot2 layer that computes and plots a stream by evaluating a
#'   one-dimensional function over a time sequence.
#'
#' @seealso [geom_function_2d_2d()] for vector fields generated from
#'   two-dimensional inputs, and \pkg{ggvfields} for the delegated stream
#'   drawing machinery.
#'
#' @examples
#' f <- function(t) {
#'   c(sin(t), cos(t))
#' }
#'
#' ggplot() + geom_function_1d_2d(fun = f)
#'
#' f <- function(t) {
#'   c(sin(t), t * cos(t))
#' }
#'
#' ggplot() +
#'   geom_function_1d_2d(fun = f, tlim = c(0, 20), tail_point = TRUE)
#'
#' f <- function(t) {
#'   x <- sin(t) * (exp(cos(t)) - 2 * cos(4 * t) - (sin(t / 12))^5)
#'   y <- cos(t) * (exp(cos(t)) - 2 * cos(4 * t) - (sin(t / 12))^5)
#'   c(x, y)
#' }
#'
#' ggplot() +
#'   geom_function_1d_2d(fun = f, tlim = c(0, 6.5), arrow = NULL, color = "black")
#'
#' f <- function(t)  c(abs(cos(t)*t), t)
#'
#' ggplot() + geom_function_1d_2d(fun = f, tlim = c(-20, 20))
#'
#' # Lissajous curve
#' lissajous <- function(t, A = 1, B = 1, a = 3, b = 2, delta = pi/2) {
#'   c(A * sin(a * t + delta), B * sin(b * t))
#' }
#'
#' ggplot() +
#'   geom_function_1d_2d(
#'     fun = lissajous, tlim = c(0, 2 * pi), color = "black", arrow = NULL,
#'     args = list(A = 1, B = 1, a = 3, b = 2, delta = pi/2)
#'   )
#'
#' # Variations on Lissajous curves
#' ggplot() +
#'   geom_function_1d_2d(
#'     fun = lissajous, tlim = c(0, 2 * pi), color = "black", arrow = NULL,
#'     args = list(A = 2, B = 1, a = 4, b = 2, delta = pi/4)
#'   )
#'
#' ggplot() +
#'   geom_function_1d_2d(
#'     fun = lissajous, tlim = c(0, 2 * pi), color = "black", arrow = NULL,
#'     args = list(A = 1, B = 2, a = 5, b = 3, delta = pi/3)
#'   )
#'
#' ggplot() +
#'   geom_function_1d_2d(
#'     fun = lissajous, tlim = c(0, 2 * pi), color = "black", arrow = NULL,
#'     args = list(A = 0.5, B = 0.5, a = 2, b = 3, delta = pi/6)
#'   )
#'
#' ggplot() +
#'   geom_function_1d_2d(
#'     fun = lissajous, tlim = c(0, 2 * pi), color = "black", arrow = NULL,
#'     args = list(A = 0.5, B = 0.5, a = 5, b = 4, delta = pi/2)
#'   )
#'
#' # Harmonic cuves
#'
#' f <- function(t,
#'   A1 = 1, A2 = 1, A3 = 1, A4 = 1,
#'   f1 = 1, f2 = 2, f3 = 3, f4 = 4,
#'   p1 = 0, p2 = pi/4, p3 = pi/2, p4 = 3*pi/4,
#'   d1 = 0.1, d2 = 0.2, d3 = 0.3, d4 = 0.4) {
#'     x <- A1 * sin(t * f1 + p1) * exp(-d1 * t) + A2 * sin(t * f2 + p2) * exp(-d2 * t)
#'     y <- A3 * sin(t * f3 + p3) * exp(-d3 * t) + A4 * sin(t * f4 + p4) * exp(-d4 * t)
#'     c(x, y)
#' }
#'
#' ggplot() + geom_function_1d_2d(fun = f, tlim = c(0, 5))
#'
#' @name geom_function_1d_2d
#' @aliases geom_function_1d_2d stat_function_1d_2d Stat_1d_2d
#' @export
#' @importFrom ggplot2 aes after_stat layer
#' @importFrom ggvfields GeomStream
#' @importFrom utils modifyList
NULL

geom_function_1d_2d <- function(mapping = NULL, data = NULL,
                              stat = Stat_1d_2d,
                              position = "identity",
                              ...,
                              na.rm = FALSE,
                              show.legend = NA,
                              inherit.aes = FALSE,
                              fun,
                              tlim = c(0, 10),
                              dt = 0.01,
                              args = list(),
                              tail_point = FALSE,
                              type = "stream",
                              arrow = NULL
) {

  if (is.null(data)) data <- ensure_nonempty_data(data)
  parameter_grid(tlim, dt)  # validate tlim/dt at construction

  # The default colour = after_stat(t) mapping is added only when the user
  # supplied neither a colour mapping nor a static colour, so a fixed
  # `colour =` in ... overrides the package default without a
  # duplicated-aesthetic warning.
  has_static_colour <- any(c("color", "colour") %in% names(list(...)))
  default_mapping <- aes(color = after_stat(t))

  if (!is.null(mapping)) {
    if (!"color" %in% names(mapping) && !"colour" %in% names(mapping) &&
        !has_static_colour)
      mapping <- modifyList(default_mapping, mapping)
  } else if (!has_static_colour) {
    mapping <- default_mapping
  } else {
    mapping <- aes()
  }

  layer(
    stat = stat,
    geom = GeomStream,
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      fun = fun,
      tlim = tlim,
      dt = dt,
      args = args,
      na.rm = na.rm,
      tail_point = tail_point,
      arrow = arrow,
      type = type,
      ...
    )
  )
}

#' @rdname geom_function_1d_2d
#' @format NULL
#' @usage NULL
#' @export
stat_function_1d_2d <- function(mapping = NULL, data = NULL,
                               geom = GeomStream,
                               position = "identity",
                               ...,
                               na.rm = FALSE,
                               show.legend = NA,
                               inherit.aes = FALSE,
                               fun,
                               tlim = c(0, 10),
                               dt = 0.01,
                               args = list(),
                               tail_point = FALSE,
                               type = "stream",
                               arrow = NULL
) {

  if (is.null(data)) data <- ensure_nonempty_data(data)
  parameter_grid(tlim, dt)  # validate tlim/dt at construction

  # The default colour = after_stat(t) mapping is added only when the user
  # supplied neither a colour mapping nor a static colour, so a fixed
  # `colour =` in ... overrides the package default without a
  # duplicated-aesthetic warning.
  has_static_colour <- any(c("color", "colour") %in% names(list(...)))
  default_mapping <- aes(color = after_stat(t))

  if (!is.null(mapping)) {
    if (!"color" %in% names(mapping) && !"colour" %in% names(mapping) &&
        !has_static_colour)
      mapping <- modifyList(default_mapping, mapping)
  } else if (!has_static_colour) {
    mapping <- default_mapping
  } else {
    mapping <- aes()
  }

  layer(
    stat = Stat_1d_2d,
    geom = geom,
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      fun = fun,
      tlim = tlim,
      dt = dt,
      args = args,
      na.rm = na.rm,
      tail_point = tail_point,
      arrow = arrow,
      type = type,
      ...
    )
  )
}

#' Regular parameter grid with `dt` as an exact positive step magnitude
#'. Regular evaluations are exactly `dt` apart; the terminal endpoint
#' is appended when the span is not an exact multiple; reversed `tlim` steps
#' in the negative direction; equal endpoints produce one evaluation.
#' @noRd
parameter_grid <- function(tlim, dt) {
  if (!is.numeric(tlim) || length(tlim) != 2L || any(!is.finite(tlim))) {
    cli::cli_abort("{.arg tlim} must be a numeric vector of two finite values.")
  }
  if (!is.numeric(dt) || length(dt) != 1L || !is.finite(dt) || dt <= 0) {
    cli::cli_abort("{.arg dt} must be a single finite positive step magnitude.")
  }
  if (tlim[1] == tlim[2]) {
    return(tlim[1])
  }
  by <- sign(tlim[2] - tlim[1]) * dt
  t <- seq(tlim[1], tlim[2], by = by)
  if (!isTRUE(all.equal(t[length(t)], tlim[2]))) {
    t <- c(t, tlim[2])
  }
  t
}

#' @rdname geom_function_1d_2d
#' @format NULL
#' @usage NULL
#' @export
Stat_1d_2d <- ggproto("Stat_1d_2d", Stat,
  default_aes = aes(color = after_stat(t)),

  compute_group = function(data, scales, fun, tlim, dt, args, ...) {

    t <- parameter_grid(tlim, dt)

    orig_fun <- fun
    fun <- function(v) rlang::inject(orig_fun(v, !!!args))

    stream_values <- t(vapply(t, fun, numeric(2)))
    x_eval <- stream_values[, 1]
    y_eval <- stream_values[, 2]

    # Positions are transformed exactly once; raw evaluations are retained
    # in t/x_eval/y_eval.
    data.frame(
      t = t,
      x = scale_forward(scales$x, x_eval),
      y = scale_forward(scales$y, y_eval),
      x_eval = x_eval,
      y_eval = y_eval
    )
  }
)
