# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit ggfunction.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 4,
  fig.align = "center",
  out.width = "85%",
  warning = FALSE,
  message = FALSE
)

options(
  ggplot2.continuous.colour = NULL,
  ggplot2.continuous.fill = NULL
)

library(ggfunction)
library(ggplot2)


## ----eval=FALSE, echo=TRUE----------------------------------------------------
# # instead of wrapping in an anonymous function:
# ggplot() + geom_pdf(fun = function(x) dnorm(x, mean = 5, sd = 2), xlim = c(0, 10))
# 
# # users can write:
# ggplot() + geom_pdf(fun = dnorm, args = list(mean = 5, sd = 2), xlim = c(0, 10))


## ----sin-curve, echo=TRUE-----------------------------------------------------
#| fig.cap: "The sine function over one full period."
ggplot() +
  geom_function_1d_1d(fun = sin, xlim = c(0, 2 * pi))


## ----shaded-normal, echo=TRUE-------------------------------------------------
#| fig.cap: "The standard normal density with the interval $[-1, 1]$ shaded, corresponding to approximately 68\\% of the total area."
ggplot() +
  geom_function_1d_1d(
    fun = dnorm, xlim = c(-3, 3),
    shade_from = -1, shade_to = 1
  )


## ----spiral, echo=TRUE--------------------------------------------------------
#| fig.cap: "A parametric spiral $\\boldsymbol{\\gamma}(t) = (\\sin t,\\; t\\cos t)$ for $t \\in [0, 20]$, with color encoding the time parameter."
f_spiral <- function(t) c(sin(t), t * cos(t))

ggplot() +
  geom_function_1d_2d(fun = f_spiral, tlim = c(0, 20), tail_point = TRUE)


## ----lissajous, echo=TRUE-----------------------------------------------------
#| fig.cap: "A Lissajous figure with frequency ratio $a/b = 3/2$ and phase offset $\\delta = \\pi/2$."
lissajous <- function(t, A = 1, B = 1, a = 3, b = 2, delta = pi/2) {
  c(A * sin(a * t + delta), B * sin(b * t))
}

ggplot() +
  geom_function_1d_2d(
    fun = lissajous, tlim = c(0, 2 * pi), arrow = NULL,
    args = list(A = 1, B = 1, a = 3, b = 2, delta = pi/2)
  )


## ----gaussian-raster, echo=TRUE-----------------------------------------------
#| fig.cap: "A Gaussian bump $f(x, y) = \\exp(-(x^2 + y^2)/2)$ rendered as a raster heatmap."
f_gaussian <- function(u) {
  x <- u[1]; y <- u[2]
  exp(-(x^2 + y^2) / 2)
}

ggplot() +
  geom_function_2d_1d(fun = f_gaussian, xlim = c(-3, 3), ylim = c(-3, 3))


## ----gaussian-contour, echo=TRUE, fig.width=10, fig.height=4------------------
#| fig.cap: "The same Gaussian bump rendered as contour lines (left) and filled contours (right)."
library("gridExtra")

p_contour <- ggplot() +
  geom_function_2d_1d(
    fun = f_gaussian, xlim = c(-3, 3), ylim = c(-3, 3), type = "contour"
  ) + ggtitle("type = \"contour\"")

p_filled <- ggplot() +
  geom_function_2d_1d(
    fun = f_gaussian, xlim = c(-3, 3), ylim = c(-3, 3), type = "contour_filled"
  ) + ggtitle("type = \"contour_filled\"")

grid.arrange(p_contour, p_filled, ncol = 2)


## ----rotation-field, echo=TRUE------------------------------------------------
#| fig.cap: "The rotation field $\\mathbf{F}(x, y) = (-y, x)$ visualized as streamlines. Each curve follows the counterclockwise flow induced by the field."
f_rotation <- function(u) {
  x <- u[1]; y <- u[2]
  c(-y, x)
}

ggplot() +
  geom_function_2d_2d(fun = f_rotation, xlim = c(-1, 1), ylim = c(-1, 1))


## ----pdf-single, echo=TRUE----------------------------------------------------
#| fig.cap: "Standard normal density with the lower 97.5\\% shaded."
ggplot() +
  geom_pdf(fun = dnorm, xlim = c(-3, 3), p = 0.975)


## ----pdf-two-sided, echo=TRUE-------------------------------------------------
#| fig.cap: "The central 95\\% of the standard normal density, corresponding to the interval between the 2.5th and 97.5th percentiles."
ggplot() +
  geom_pdf(
    fun = dnorm, xlim = c(-3, 3),
    p_lower = 0.025, p_upper = 0.975
  )


## ----pdf-tails, echo=TRUE-----------------------------------------------------
#| fig.cap: "The rejection region of a two-sided test at $\\alpha = 0.05$, shading the area outside the central 95\\%."
ggplot() +
  geom_pdf(
    fun = dnorm, xlim = c(-3, 3),
    p_lower = 0.025, p_upper = 0.975, shade_outside = TRUE
  )


## ----cdf-shaded, echo=TRUE----------------------------------------------------
#| fig.cap: "The standard normal CDF with the region below $p = 0.975$ shaded."
ggplot() +
  geom_cdf(fun = pnorm, xlim = c(-3, 3), p = 0.975)


## ----pmf-binomial, echo=TRUE--------------------------------------------------
#| fig.cap: "The PMF of a $\\mathrm{Binomial}(10, 0.3)$ distribution, rendered as a lollipop chart."
ggplot() +
  geom_pmf(fun = dbinom, args = list(size = 10, prob = 0.3), xlim = c(0, 10))


## ----qf-normal, echo=TRUE-----------------------------------------------------
#| fig.cap: "The quantile function of the standard normal distribution."
ggplot() +
  geom_qf(fun = qnorm)


## ----discrete-cdf, echo=TRUE--------------------------------------------------
#| fig.cap: "The discrete CDF of a $\\mathrm{Binomial}(10, 0.5)$ distribution with the region below $p = 0.9$ shaded."
ggplot() +
  geom_discrete_cdf(
    fun = dbinom, args = list(size = 10, prob = 0.5),
    xlim = c(0, 10), p = 0.9
  )


## ----survival-exp, echo=TRUE--------------------------------------------------
#| fig.cap: "The survival function of an $\\mathrm{Exponential}(0.5)$ distribution, $S(x) = e^{-0.5x}$."
ggplot() +
  geom_survival(fun = pexp, args = list(rate = 0.5), xlim = c(0, 10))


## ----hazard-exp, echo=TRUE----------------------------------------------------
#| fig.cap: "The hazard function of an $\\mathrm{Exponential}(0.5)$ distribution, constant at $h(x) = 0.5$--a consequence of the memoryless property."
ggplot() +
  geom_hf(
    pdf_fun = dexp, cdf_fun = pexp,
    args = list(rate = 0.5), xlim = c(0.01, 10)
  )


## ----hazard-normal, echo=TRUE-------------------------------------------------
#| fig.cap: "The increasing hazard function of the standard normal distribution."
ggplot() +
  geom_hf(
    pdf_fun = dnorm, cdf_fun = pnorm,
    args = list(mean = 0, sd = 1), xlim = c(-3, 3)
  )


## ----eval=FALSE, echo=TRUE----------------------------------------------------
# fun_injected <- function(x) {
#   rlang::inject(fun(x, !!!args))
# }


## ----composability, echo=TRUE-------------------------------------------------
#| fig.cap: "Two normal densities with different means and spreads overlaid in a single plot, demonstrating composability with the ggplot2 grammar of graphics."
ggplot() +
  geom_pdf(
    fun = dnorm, args = list(mean = 0, sd = 1),
    xlim = c(-5, 8), alpha = 0.4
  ) +
  geom_pdf(
    fun = dnorm, args = list(mean = 3, sd = 1.5),
    xlim = c(-5, 8), alpha = 0.4
  ) +
  labs(x = "x", y = "f(x)", title = "Comparing two normal densities") +
  theme_minimal()


## ----echo=FALSE, results="asis"-----------------------------------------------
pkg_list <- c("ggplot2", "rlang", "cli")
for (pkg in pkg_list) {
  if (requireNamespace(pkg, quietly = TRUE)) invisible(NULL)
}

