# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit ggfunction.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE,
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 3,
  fig.align = "center",
  out.width = "85%",
  warning = FALSE,
  message = FALSE
)

options(
  ggplot2.continuous.colour = NULL,
  ggplot2.continuous.fill = NULL
)

library(ggfunction)
library(ggplot2)
library(patchwork)


## ----eval=FALSE, echo=TRUE----------------------------------------------------
# # instead of wrapping in an anonymous function:
# ggplot() + geom_pdf(fun = function(x) dnorm(x, mean = 5, sd = 2), xlim = c(0, 10))
# 
# # users can write:
# ggplot() + geom_pdf(fun = dnorm, xlim = c(0, 10), args = list(mean = 5, sd = 2))


## ----sin-curve, echo=TRUE-----------------------------------------------------
#| fig.cap: "The sine function over one full period."
library("ggfunction")

ggplot() +
  geom_function_1d_1d(fun = sin, xlim = c(0, 2 * pi))


## ----shaded-cosine, echo=TRUE-------------------------------------------------
#| fig.cap: "The cosine function over $[0, 2\\pi]$ with the interval $[0, \\pi/2]$ shaded; the shaded area equals $\\int_0^{\\pi/2} \\cos(x)\\,dx = 1$."
ggplot() +
  geom_function_1d_1d(
    fun = cos, xlim = c(0, 2 * pi),
    shade_from = 0, shade_to = pi / 2
  )


## ----lemniscate, echo=TRUE----------------------------------------------------
#| fig.cap: "The lemniscate of Bernoulli $\\boldsymbol{\\gamma}(t) = (\\cos t\\,/\\,(1+\\sin^2 t),\\; \\sin t\\cos t\\,/\\,(1+\\sin^2 t))$--a figure-eight curve along which the product of distances to the two foci is constant--with color encoding the parameter $t$."
lemniscate <- function(t) c(cos(t) / (1 + sin(t)^2), sin(t) * cos(t) / (1 + sin(t)^2))

ggplot() +
  geom_function_1d_2d(fun = lemniscate, tlim = c(0, 1.9 * pi), tail_point = TRUE)


## ----lissajous, echo=TRUE, fig.width=10, fig.height=4-------------------------
#| fig.cap: "Lissajous figures $\\boldsymbol{\\gamma}(t) = (\\sin(at + \\pi/2),\\,\\sin(bt))$ for three frequency ratios $a/b$. Each ratio produces a qualitatively distinct closed curve; the same function definition is reused across all three panels via the \\texttt{args} parameter."
lissajous <- function(t, a = 3, b = 2, delta = pi/2) {
  c(sin(a * t + delta), sin(b * t))
}

p1 <- ggplot() +
  geom_function_1d_2d(
    fun = lissajous, tlim = c(0, 1.9 * pi),
    args = list(a = 1, b = 1)
  ) + ggtitle("a = 1, b = 1")

p2 <- ggplot() +
  geom_function_1d_2d(
    fun = lissajous, tlim = c(0, 1.9 * pi),
    args = list(a = 2, b = 1)
  ) + ggtitle("a = 2, b = 1")

p3 <- ggplot() +
  geom_function_1d_2d(
    fun = lissajous, tlim = c(0, 1.9 * pi),
    args = list(a = 3, b = 2)
  ) + ggtitle("a = 3, b = 2")

(p1 | p2 | p3) + plot_layout(guides = "collect")


## ----sincos-raster, echo=TRUE-------------------------------------------------
#| fig.cap: "The function $f(x, y) = \\sin(x)\\cos(y)$ over $[-\\pi, \\pi]^2$ rendered as a raster heatmap."
f_sc <- function(u) {
  x <- u[1]; y <- u[2]
  sin(x) * cos(y)
}

ggplot() +
  geom_function_2d_1d(fun = f_sc, xlim = c(-pi, pi), ylim = c(-pi, pi))


## ----sincos-contour, echo=TRUE, fig.width=10, fig.height=4--------------------
#| fig.cap: "The same function rendered as contour lines (left) and filled contours (right)."
p_contour <- ggplot() +
  geom_function_2d_1d(
    fun = f_sc, xlim = c(-pi, pi), ylim = c(-pi, pi), type = "contour"
  ) + ggtitle("type = \"contour\"")

p_filled <- ggplot() +
  geom_function_2d_1d(
    fun = f_sc, xlim = c(-pi, pi), ylim = c(-pi, pi), type = "contour_filled"
  ) + ggtitle("type = \"contour_filled\"")

p_contour | p_filled


## ----rotation-field, echo=TRUE------------------------------------------------
#| fig.cap: "The rotation field $\\mathbf{F}(x, y) = (-y, x)$ displayed as short arrows at each grid point."
f_rotation <- function(u) {
  x <- u[1]; y <- u[2]
  c(-y, x)
}

ggplot() +
  geom_function_2d_2d(fun = f_rotation, xlim = c(-1, 1), ylim = c(-1, 1))


## ----rotation-stream, echo=TRUE-----------------------------------------------
#| fig.cap: "The same rotation field rendered as streamlines, each following the counterclockwise flow induced by the field."
ggplot() +
  geom_function_2d_2d(fun = f_rotation, xlim = c(-1, 1), ylim = c(-1, 1),
    type = "stream")


## ----pdf-shading-modes, echo=TRUE, fig.width=10, fig.height=4-----------------
#| fig.cap: "Three shading modes for \\texttt{geom\\_pdf()}: lower tail ($p = 0.975$, left), central 95\\% interval (center), and two-tailed rejection region at $\\alpha = 0.05$ (right)."
p1 <- ggplot() +
  geom_pdf(fun = dnorm, xlim = c(-3, 3), p = 0.975) +
  ggtitle("p = 0.975")

p2 <- ggplot() +
  geom_pdf(
    fun = dnorm, xlim = c(-3, 3),
    p_lower = 0.025, p_upper = 0.975
  ) + ggtitle("Central 95%")

p3 <- ggplot() +
  geom_pdf(
    fun = dnorm, xlim = c(-3, 3),
    p_lower = 0.025, p_upper = 0.975, shade_outside = TRUE
  ) + ggtitle("\u03b1 = 0.05 rejection region")

p1 | p2 | p3


## ----pdf-hdr, echo=TRUE-------------------------------------------------------
#| fig.cap: "The 80\\% highest density region of an asymmetric bimodal density ($0.6\\,\\mathcal{N}(-2,\\,0.6^2) + 0.4\\,\\mathcal{N}(2,\\,1.2^2)$), shading both modes as two disjoint intervals with more area allocated to the taller, narrower component."
f_mix <- function(x) 0.6 * dnorm(x, mean = -2, sd = 0.6) + 0.4 * dnorm(x, mean = 2, sd = 1.2)
ggplot() +
  geom_pdf(fun = f_mix, xlim = c(-5, 6), shade_hdr = 0.8)


## ----pmf-binomial, echo=TRUE--------------------------------------------------
#| fig.cap: "The PMF of a $\\mathrm{Binomial}(10, 0.3)$ distribution, rendered as a lollipop chart."
ggplot() +
  geom_pmf(fun = dbinom, xlim = c(0, 10), args = list(size = 10, prob = 0.3))


## ----pmf-clt, echo=TRUE-------------------------------------------------------
#| fig.cap: "Exact distribution of the sample mean of 10 i.i.d.~Bernoulli(0.3) draws (lollipops) with the CLT normal approximation overlaid as a scaled density curve."
p <- 0.3; n <- 10
sd_mean <- sqrt(p * (1 - p) / n)
f_mean  <- function(x) dbinom(round(x * n), size = n, prob = p)
max_pmf <- max(f_mean(seq(0, 1, by = 1/n)))
scale   <- max_pmf / dnorm(p, mean = p, sd = sd_mean)
f_clt   <- function(x) scale * dnorm(x, mean = p, sd = sd_mean)

ggplot() +
  geom_pmf(fun = f_mean, support = seq(0, 1, by = 1/n)) +
  geom_pdf(fun = f_clt, xlim = c(0, 1))


## ----pmf-shading, echo=TRUE---------------------------------------------------
#| fig.cap: "Shading modes for \\texttt{geom\\_pmf()}: the lower 80\\% by cumulative probability (left) and the 80\\% HDR of a $\\mathrm{Binomial}(10, 0.3)$ distribution (right). Unshaded lollipops are shown in grey."
p1 <- ggplot() +
  geom_pmf(fun = dbinom, xlim = c(0, 10),
    args = list(size = 10, prob = 0.5), p = 0.8) +
  ggtitle("p = 0.8")

p2 <- ggplot() +
  geom_pmf(fun = dbinom, xlim = c(0, 10),
    args = list(size = 10, prob = 0.3), shade_hdr = 0.8) +
  ggtitle("shade_hdr = 0.8")

p1 | p2


## ----cdf-shaded, echo=TRUE----------------------------------------------------
#| fig.cap: "The standard normal CDF."
ggplot() +
  geom_cdf(fun = pnorm, xlim = c(-3, 3))


## ----discrete-cdf, echo=TRUE--------------------------------------------------
#| fig.cap: "The discrete CDF of a $\\mathrm{Binomial}(10, 0.5)$ distribution."
ggplot() +
  geom_cdf_discrete(
    fun = dbinom, xlim = c(0, 10), args = list(size = 10, prob = 0.5)
  )


## ----survival-exp, echo=TRUE--------------------------------------------------
#| fig.cap: "The survival function of an $\\mathrm{Exponential}(0.5)$ distribution, $S(x) = e^{-0.5x}$."
ggplot() +
  geom_survival(fun = pexp, xlim = c(0, 10), args = list(rate = 0.5))


## ----discrete-survival, echo=TRUE---------------------------------------------
#| fig.cap: "The discrete survival function of a $\\mathrm{Binomial}(10, 0.5)$ distribution, descending from 1 to 0."
ggplot() +
  geom_survival_discrete(
    fun = dbinom, xlim = c(0, 10), args = list(size = 10, prob = 0.5)
  )


## ----qf-normal, echo=TRUE-----------------------------------------------------
#| fig.cap: "The quantile function of the standard normal distribution."
ggplot() +
  geom_qf(fun = qnorm)


## ----discrete-qf, echo=TRUE---------------------------------------------------
#| fig.cap: "The discrete quantile function of a $\\mathrm{Binomial}(10, 0.5)$ distribution as a left-continuous step function on $[0, 1]$."
ggplot() +
  geom_qf_discrete(
    fun = dbinom, xlim = c(0, 10), args = list(size = 10, prob = 0.5)
  )


## ----hazard-shapes, echo=TRUE, fig.width=10, fig.height=4---------------------
#| fig.cap: "Three canonical hazard shapes: decreasing ($\\mathrm{Weibull}(\\mathrm{shape}{=}0.5,\\,\\mathrm{scale}{=}2)$, left), constant ($\\mathrm{Exponential}(0.5)$, center), and increasing ($\\mathcal{N}(0,1)$, right)."
p_decr <- ggplot() +
  geom_hf(
    pdf_fun = dweibull, cdf_fun = pweibull,
    xlim = c(0.01, 5), args = list(shape = 0.5, scale = 2)
  ) + ggtitle("Decreasing (Weibull)")

p_flat <- ggplot() +
  geom_hf(
    pdf_fun = dexp, cdf_fun = pexp,
    xlim = c(0.01, 10), args = list(rate = 0.5)
  ) + ggtitle("Flat (Exponential)")

p_incr <- ggplot() +
  geom_hf(
    pdf_fun = dnorm, cdf_fun = pnorm,
    xlim = c(-3, 3), args = list(mean = 0, sd = 1)
  ) + ggtitle("Increasing (Normal)")

p_decr | p_flat | p_incr


## ----eval=FALSE, echo=TRUE----------------------------------------------------
# fun_injected <- function(x) {
#   rlang::inject(fun(x, !!!args))
# }


## ----composability, echo=TRUE-------------------------------------------------
#| fig.cap: "Two normal densities with different means and spreads overlaid in a single plot, demonstrating composability with the ggplot2 grammar of graphics."
ggplot() +
  geom_pdf(
    fun = dnorm, xlim = c(-5, 8),
    args = list(mean = 0, sd = 1), alpha = 0.4
  ) +
  geom_pdf(
    fun = dnorm, xlim = c(-5, 8),
    args = list(mean = 3, sd = 1.5), alpha = 0.4
  ) +
  labs(x = "x", y = "f(x)", title = "Comparing two normal densities") +
  theme_minimal()


## ----echo=FALSE, results="asis"-----------------------------------------------
pkg_list <- c("ggplot2", "rlang", "cli")
for (pkg in pkg_list) {
  if (requireNamespace(pkg, quietly = TRUE)) invisible(NULL)
}

